# Generated by Django 4.0.2 on 2022-02-08 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_object_end_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='end_auction',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 8, 12, 1, 55, 741530)),
        ),
    ]
