# Generated by Django 4.0.2 on 2022-02-09 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_object_end_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='end_auction',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 18, 19, 50, 263329)),
        ),
        migrations.AlterField(
            model_name='object',
            name='status',
            field=models.CharField(default='open', max_length=5),
        ),
    ]
