# Generated by Django 4.0.2 on 2022-02-09 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_object_end_auction_alter_object_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='end_auction',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 18, 27, 47, 788287)),
        ),
    ]
