# Generated by Django 4.0.2 on 2022-02-09 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_object_end_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='end_auction',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 18, 33, 21, 545438)),
        ),
    ]
