# Generated by Django 4.0.2 on 2022-02-10 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_object_end_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='end_auction',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 17, 18, 10, 35071)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 17, 18, 10, 33067)),
        ),
    ]
