# Generated by Django 4.0.2 on 2022-02-10 16:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_object_end_auction_alter_profile_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('starting_price', models.FloatField(default=0)),
                ('buy_now', models.FloatField(default=0)),
                ('end_auction', models.DateTimeField(default=datetime.datetime(2022, 2, 10, 17, 50, 54, 149903))),
                ('offer', models.FloatField(default=0)),
                ('status', models.CharField(default='open', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 17, 50, 54, 148902)),
        ),
        migrations.DeleteModel(
            name='Object',
        ),
        migrations.AddField(
            model_name='shoes',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
    ]
