# Generated by Django 4.0.2 on 2022-02-11 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_shoes_alter_profile_last_login_delete_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='hash',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='txId',
            field=models.CharField(default=None, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 10, 28, 13, 562335)),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='end_auction',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 10, 28, 13, 563337)),
        ),
    ]
