# Generated by Django 4.0.2 on 2022-02-12 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_profile_last_login_alter_shoes_end_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 7, 44, 58, 51179)),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='end_auction',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 7, 44, 58, 53179)),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='hash',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='txId',
            field=models.CharField(blank=True, default=None, max_length=66, null=True),
        ),
    ]
